#!/bin/bash

echo "Generating .env.production file..."

cat <<EOT > .env.production
VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
VITE_LINKEDIN_CLIENT_ID=$VITE_LINKEDIN_CLIENT_ID
VITE_BASE_URL=$VITE_BASE_URL
VITE_GEMINI_URL=$VITE_GEMINI_URL
VITE_GEMINI_API_KEY=$VITE_GEMINI_API_KEY

# Firebase configuration
VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY
VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN
VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID
VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET
VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID
VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID
VITE_FIREBASE_VAPID_KEY=$VITE_FIREBASE_VAPID_KEY

EOT

echo ".env.production file created successfully!"