name: Vite React Frontend CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint
      run: npm run lint
      
    - name: Check code formatting
      run: npx prettier --check "src/**/*.{js,jsx,ts,tsx}"
    
    - name: Run tests
      run: npm run test
    
    - name: Build verification
      run: npm run build
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/
        retention-days: 5

  code-quality:
    runs-on: ubuntu-latest
    needs: lint-test-build
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=your-organization_your-project
          -Dsonar.organization=your-organization
          -Dsonar.sources=src
          -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info

  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Check for vulnerabilities
      run: npm audit --production
